version: "3"

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    env_file:
      - .env
    networks:
      - mysql-phpmyadmin
  adminer:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      - 8080:8080

networks:
  mysql-phpmyadmin:

volumes:
  db_data: